// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/cryptalias/v1/asset_resolver.proto

package cryptaliasv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssetResolver_GetAddress_FullMethodName = "/cryptalias.v1.AssetResolver/GetAddress"
	AssetResolver_Health_FullMethodName     = "/cryptalias.v1.AssetResolver/Health"
)

// AssetResolverClient is the client API for AssetResolver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssetResolverClient interface {
	GetAddress(ctx context.Context, in *WalletAddressRequest, opts ...grpc.CallOption) (*WalletAddressResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type assetResolverClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetResolverClient(cc grpc.ClientConnInterface) AssetResolverClient {
	return &assetResolverClient{cc}
}

func (c *assetResolverClient) GetAddress(ctx context.Context, in *WalletAddressRequest, opts ...grpc.CallOption) (*WalletAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletAddressResponse)
	err := c.cc.Invoke(ctx, AssetResolver_GetAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetResolverClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AssetResolver_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetResolverServer is the server API for AssetResolver service.
// All implementations must embed UnimplementedAssetResolverServer
// for forward compatibility.
type AssetResolverServer interface {
	GetAddress(context.Context, *WalletAddressRequest) (*WalletAddressResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedAssetResolverServer()
}

// UnimplementedAssetResolverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssetResolverServer struct{}

func (UnimplementedAssetResolverServer) GetAddress(context.Context, *WalletAddressRequest) (*WalletAddressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAddress not implemented")
}
func (UnimplementedAssetResolverServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAssetResolverServer) mustEmbedUnimplementedAssetResolverServer() {}
func (UnimplementedAssetResolverServer) testEmbeddedByValue()                       {}

// UnsafeAssetResolverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetResolverServer will
// result in compilation errors.
type UnsafeAssetResolverServer interface {
	mustEmbedUnimplementedAssetResolverServer()
}

func RegisterAssetResolverServer(s grpc.ServiceRegistrar, srv AssetResolverServer) {
	// If the following call panics, it indicates UnimplementedAssetResolverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssetResolver_ServiceDesc, srv)
}

func _AssetResolver_GetAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetResolverServer).GetAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetResolver_GetAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetResolverServer).GetAddress(ctx, req.(*WalletAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetResolver_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetResolverServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetResolver_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetResolverServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetResolver_ServiceDesc is the grpc.ServiceDesc for AssetResolver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetResolver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cryptalias.v1.AssetResolver",
	HandlerType: (*AssetResolverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAddress",
			Handler:    _AssetResolver_GetAddress_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _AssetResolver_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cryptalias/v1/asset_resolver.proto",
}
