// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/cryptalias/v1/wallet_service.proto

package cryptaliasv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WalletAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Domain        string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	AccountIndex  *uint64                `protobuf:"varint,5,opt,name=account_index,json=accountIndex,proto3,oneof" json:"account_index,omitempty"`
	AccountId     *string                `protobuf:"bytes,6,opt,name=account_id,json=accountId,proto3,oneof" json:"account_id,omitempty"`
	WalletId      *string                `protobuf:"bytes,7,opt,name=wallet_id,json=walletId,proto3,oneof" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletAddressRequest) Reset() {
	*x = WalletAddressRequest{}
	mi := &file_proto_cryptalias_v1_wallet_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletAddressRequest) ProtoMessage() {}

func (x *WalletAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cryptalias_v1_wallet_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletAddressRequest.ProtoReflect.Descriptor instead.
func (*WalletAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_cryptalias_v1_wallet_service_proto_rawDescGZIP(), []int{0}
}

func (x *WalletAddressRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *WalletAddressRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *WalletAddressRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *WalletAddressRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *WalletAddressRequest) GetAccountIndex() uint64 {
	if x != nil && x.AccountIndex != nil {
		return *x.AccountIndex
	}
	return 0
}

func (x *WalletAddressRequest) GetAccountId() string {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return ""
}

func (x *WalletAddressRequest) GetWalletId() string {
	if x != nil && x.WalletId != nil {
		return *x.WalletId
	}
	return ""
}

type WalletAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletAddressResponse) Reset() {
	*x = WalletAddressResponse{}
	mi := &file_proto_cryptalias_v1_wallet_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletAddressResponse) ProtoMessage() {}

func (x *WalletAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cryptalias_v1_wallet_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletAddressResponse.ProtoReflect.Descriptor instead.
func (*WalletAddressResponse) Descriptor() ([]byte, []int) {
	return file_proto_cryptalias_v1_wallet_service_proto_rawDescGZIP(), []int{1}
}

func (x *WalletAddressResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_cryptalias_v1_wallet_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cryptalias_v1_wallet_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_cryptalias_v1_wallet_service_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_cryptalias_v1_wallet_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cryptalias_v1_wallet_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_cryptalias_v1_wallet_service_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_cryptalias_v1_wallet_service_proto protoreflect.FileDescriptor

const file_proto_cryptalias_v1_wallet_service_proto_rawDesc = "" +
	"\n" +
	"(proto/cryptalias/v1/wallet_service.proto\x12\rcryptalias.v1\"\x8d\x02\n" +
	"\x14WalletAddressRequest\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12(\n" +
	"\raccount_index\x18\x05 \x01(\x04H\x00R\faccountIndex\x88\x01\x01\x12\"\n" +
	"\n" +
	"account_id\x18\x06 \x01(\tH\x01R\taccountId\x88\x01\x01\x12 \n" +
	"\twallet_id\x18\a \x01(\tH\x02R\bwalletId\x88\x01\x01B\x10\n" +
	"\x0e_account_indexB\r\n" +
	"\v_account_idB\f\n" +
	"\n" +
	"_wallet_id\"1\n" +
	"\x15WalletAddressResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x0f\n" +
	"\rHealthRequest\":\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xaf\x01\n" +
	"\rWalletService\x12W\n" +
	"\n" +
	"GetAddress\x12#.cryptalias.v1.WalletAddressRequest\x1a$.cryptalias.v1.WalletAddressResponse\x12E\n" +
	"\x06Health\x12\x1c.cryptalias.v1.HealthRequest\x1a\x1d.cryptalias.v1.HealthResponseB?Z=github.com/kaigoh/cryptalias/proto/cryptalias/v1;cryptaliasv1b\x06proto3"

var (
	file_proto_cryptalias_v1_wallet_service_proto_rawDescOnce sync.Once
	file_proto_cryptalias_v1_wallet_service_proto_rawDescData []byte
)

func file_proto_cryptalias_v1_wallet_service_proto_rawDescGZIP() []byte {
	file_proto_cryptalias_v1_wallet_service_proto_rawDescOnce.Do(func() {
		file_proto_cryptalias_v1_wallet_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cryptalias_v1_wallet_service_proto_rawDesc), len(file_proto_cryptalias_v1_wallet_service_proto_rawDesc)))
	})
	return file_proto_cryptalias_v1_wallet_service_proto_rawDescData
}

var file_proto_cryptalias_v1_wallet_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_cryptalias_v1_wallet_service_proto_goTypes = []any{
	(*WalletAddressRequest)(nil),  // 0: cryptalias.v1.WalletAddressRequest
	(*WalletAddressResponse)(nil), // 1: cryptalias.v1.WalletAddressResponse
	(*HealthRequest)(nil),         // 2: cryptalias.v1.HealthRequest
	(*HealthResponse)(nil),        // 3: cryptalias.v1.HealthResponse
}
var file_proto_cryptalias_v1_wallet_service_proto_depIdxs = []int32{
	0, // 0: cryptalias.v1.WalletService.GetAddress:input_type -> cryptalias.v1.WalletAddressRequest
	2, // 1: cryptalias.v1.WalletService.Health:input_type -> cryptalias.v1.HealthRequest
	1, // 2: cryptalias.v1.WalletService.GetAddress:output_type -> cryptalias.v1.WalletAddressResponse
	3, // 3: cryptalias.v1.WalletService.Health:output_type -> cryptalias.v1.HealthResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cryptalias_v1_wallet_service_proto_init() }
func file_proto_cryptalias_v1_wallet_service_proto_init() {
	if File_proto_cryptalias_v1_wallet_service_proto != nil {
		return
	}
	file_proto_cryptalias_v1_wallet_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cryptalias_v1_wallet_service_proto_rawDesc), len(file_proto_cryptalias_v1_wallet_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cryptalias_v1_wallet_service_proto_goTypes,
		DependencyIndexes: file_proto_cryptalias_v1_wallet_service_proto_depIdxs,
		MessageInfos:      file_proto_cryptalias_v1_wallet_service_proto_msgTypes,
	}.Build()
	File_proto_cryptalias_v1_wallet_service_proto = out.File
	file_proto_cryptalias_v1_wallet_service_proto_goTypes = nil
	file_proto_cryptalias_v1_wallet_service_proto_depIdxs = nil
}
